### ISSUE TITLE
New version on its way

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#264]
Hello

I have been working at a new version these last months. And I need testers now, before I can release it on silex.me

[![screen shot 2015-04-22 at 10 24 24 am](https://cloud.githubusercontent.com/assets/715377/7270110/d463dde6-e8d9-11e4-997b-ad585c64b032.png)](http://preprod.silex.me/)

Here is where you can test it: http://preprod.silex.me/
And if you edit a website with this version, do not go back and edit the same website with the old version on editor.silex.me. You will have to continue on preprod until I have released the version.

And @mrqproductions @ameliepic @jaylamhill @barkingPete @internetimagery @blauer @Hans3901 @withnoe, you can click on the "watch" button in order to be notified when there is a news or a question :)
![screen shot 2015-04-22 at 10 06 04 am](https://cloud.githubusercontent.com/assets/715377/7269812/4eab4bc8-e8d7-11e4-971b-35d6d4c26744.png)

Here is what changed in this new version (you do not have to read all this, you may want to simply test all of it on [preprod](http://preprod.silex.me/)

* better preview and a new preview option in [responsize](http://www.responsize.org)
* new selection UI on the stage
* changed the way to move elements up / down (z-index)
* fixed publication on FTP
* better UI (properties panel, menu...)
* CSS: no need to add !important anymore 
* undo / redo: a lot quicker
* desktop notifications (displays messages outside the browser)
* added HEAD tag editor
* added social network meta data in settings
* added favicon and description to the site settings panel
* added switch button for apollo mode in the properties
* the generated HTML code is better

**Comment by Hans3901** [comment]
Hi Alex,

I'm pleased to help. My first comment is: Position and size arrows do not work (Chrome)

Kind regards,

Hans Visser

----- Oorspronkelijk bericht -----
Van: "Alex Hoyau" <notifications@github.com>
Aan: "silexlabs/Silex" <Silex@noreply.github.com>
Cc: "Hans3901" <hem.visser@online.nl>
Verzonden: Woensdag 22 april 2015 10:25:37
Onderwerp: [Silex] New version on its way (#264)



Hello 

I have been working at a new version these last months. And I need testers now, before I can release it on silex.me 

screen shot 2015-04-22 at 10 24 24 am

Here is where you can test it: http://preprod.silex.me/ 
And if you edit a website with this version, do not go back and edit the same website with the old version on editor.silex.me. You will have to continue on preprod until I have released the version. 

And @mrqproductions @ameliepic @jaylamhill @barkingPete @internetimagery @blauer @Hans3901 @withnoe , you can click on the "watch" button in order to be notified when there is a news or a question :) 
screen shot 2015-04-22 at 10 06 04 am

Here is what changed in this new version (you do not have to read all this, you may want to simply test all of it on preprod 

    • better preview and a new preview option in responsize 
    • new selection UI on the stage 
    • changed the way to move elements up / down (z-index) 
    • fixed publication on FTP 
    • better UI (properties panel, menu...) 
    • CSS: no need to add !important anymore 
    • undo / redo: a lot quicker 
    • desktop notifications (displays messages outside the browser) 
    • added HEAD tag editor 
    • added social network meta data in settings 
    • added favicon and description to the site settings panel 
    • added switch button for apollo mode in the properties 
    • the generated HTML code is better

**Comment by lexoyo** [comment]
Thank you for taking the time @Hans3901 :)

> Position and size arrows do not work (Chrome)

You mean the keyboard? It works here, not sure what you mean though

**Comment by AndreaMonzini** [comment]
Hello,
thank you very much for the interesting project.
i'm testing the new version of Silex and i noticed that the  "Properties" window do not resize like in the previous version but it creates windows tiles that can be useful but not for the "styles" section where is more difficult to read and modify the CSS code in comparison to the the previous version.
Thank you,

Andrea

**Comment by lexoyo** [comment]
Hi @AndreaMonzini 
Do you mean that I should make the "inline" CSS box 100% of the width of the properties panel?

**Comment by lexoyo** [comment]
Like this?
![screen shot 2015-05-13 at 10 26 49](https://cloud.githubusercontent.com/assets/715377/7606604/97af1d2a-f95a-11e4-8234-b9a8763aa85d.png)

**Comment by AndreaMonzini** [comment]
Yes, in my opinion the code  would be much more readable.
Thank you !

**Comment by singchan** [comment]
Ok I'll do that, thank you so much for your feedback, I appreciate it :)

**Comment by lexoyo** [comment]
Ok I'll do that, thank you so much for your feedback, I appreciate it :)

**Comment by AndreaMonzini** [comment]
Hello, i'm continuing to test the new verion of Silex with the template "minimal-grey" but

- i'm not able to publish to a new folder ( it works with the old version )
  Even with  a new project i'm not able to publish.
- i'm not able to edit the menu or title, when i click on menu a new preview window opens automatically  ( it works with the old version ).

Thank you for the support.

**Comment by lexoyo** [comment]
Ok, I knew there were some bugs somewher! :boat: 
I'll fix these 2 ones soon and let you know here
If you find more, I'll have to buy you a beer ;)

**Comment by lexoyo** [comment]
Hello
I have fixed these issues and deployed it to [prerod](http://preprod.silex.me/)
Please tell me if it works :sunrise: 

> I can publish overwriting original folder but i'm not able to publish to a new folder . Even with a new project i'm not able to publish ( it works with the old version).

https://github.com/lexoyo/Silex/commit/b19accbe02bce4a22de00138d27a8cb8207e6a0c

> i'm not able to edit the menu or title, when i click on menu a new preview window opens automatically ( it works with the old version ).

https://github.com/lexoyo/Silex/commit/9d067d897b998124e86eae8872a92db4ac7f0ff3

>> Do you mean that I should make the "inline" CSS box 100% of the width of the properties panel? 
> Yes, in my opinion the code would be much more readable.

https://github.com/lexoyo/Silex/commit/821882d0e2a250a61469b79166cd14525a6528a4

And I will find a better way to arrange the tiles

**Comment by AndreaMonzini** [comment]
Hello, i just tested the last version:
- Now i am able to publish to a new folder.  Great !
- CSS box is now more readable. Great !

-  I still have problem with menu editing when i test the template "minimal-grey" because as soon i click a linked object ( with white hand cursor) the Silex main window become like the a preview and i can't continue to edit the page or change pages.

In any case thank you !

Andrea

**Comment by lexoyo** [comment]
Thx @AndreaMonzini I'll get the last one soon :)

**Comment by lexoyo** [comment]
@AndreaMonzini its fixed for good this time (the links) 
http://preprod.silex.me/

Thank you for your help!
No more bugs?

**Comment by AndreaMonzini** [comment]
Now it works . Great!

I have some problems ( works only time to time) with:
Bring to front
Bring forward
Bring backward
Sent to back

**Comment by Hans3901** [comment]
Hi Alex, 

After saving to view a site, the links on this site to go to another page do not work any more. :-(((( This hapens in tjhe old as the new version! What to do? 

Hans Visser

**Comment by lexoyo** [comment]
@Hans3901 can you share the site with me on dropbox? (a.hoyau [at] im-paris.fr)
And no matter what, do not save on preprod.silex.me and then open the saved site with editor.silex.me

**Comment by Hans3901** [comment]
Hi Alex, 

The problem is gone . Another question is how to make an sign up emailform. Is there a tutorial or script? 

Kind regards, 
Hans Visser 

----- Oorspronkelijk bericht -----

Van: "Alex Hoyau" <notifications@github.com> 
Aan: "silexlabs/Silex" <Silex@noreply.github.com> 
Cc: "Hans3901" <hem.visser@online.nl> 
Verzonden: Maandag 25 mei 2015 14:46:28 
Onderwerp: Re: [Silex] New version on its way (#264) 



@Hans3901 can you share the site with me on dropbox? (a.hoyau [at] im-paris.fr) 
And no matter what, do not save on preprod.silex.me and then open the saved site with editor.silex.me

**Comment by singchan** [comment]
I use mailchimp to generate a subscription form. Then paste it in an html
box in Silex. It works with google form too.

Tell me if you need more info

**Comment by lexoyo** [comment]
a new version deployed on http://preprod.silex.me
lot of bug fixes: https://github.com/lexoyo/Silex/commits/master

**Comment by AndreaMonzini** [comment]
I'm testing the last version and it seems to work very well !

**Comment by AndreaMonzini** [comment]
Hello,
i lost all image reference in the editable html  i am working on with Silex.
So i recovered manually the link of the images replacing all the links from the wrong path "src="../../../../../Silex/ " to the old path "src="../..//Silex/"

Could you check please the bug? ( i'm using dropbox)
Thank you.

**Comment by lexoyo** [comment]
> Do you plan to add a snap function?
> For now i try to align elements manually with x,y coordinates.

I thought about it but did not prioritise it :-/
you can make an issue with this and see if some people :+1: it?

> i lost all image reference in the editable html i am working on with Silex.
> So i recovered manually almost all the right path of the images replacing all the links from the wrong path "src="../../../../../Silex/ " to the path "src="../..//Silex/" that i found in an old saved file of the project.

wow, ok I'll investigate
was it on editor.silex.me or preprod.silex.me ?

**Comment by AndreaMonzini** [comment]
preprod.silex.me 
Firefox 38.0.5

Thank you.

**Comment by samashley** [comment]
Hi, this is just to say that I only discovered silex yesterday, so probably I should use it a bit before jumping in with testing the newest version, just to get familiar with it. But wow!! A nice program! Thanks for making it available!!!

**Comment by AndreaMonzini** [comment]
Hello,
unfortunately i lost again all image references using preprod.silex.me, Firefox 38.0.5 and Dropbox.

**Comment by lexoyo** [comment]
I could not fix the bug yet
I have found a solution but quite long to implement
I'll come back to you with a fix, sorry about that

**Comment by lexoyo** [comment]
Thank you @samashley 
Do not hesitate to create an issue with your thoughts as a beginner

**Comment by lexoyo** [comment]
Ok, I think we are really close to a new release
The version on [preprod.silex.me](http://preprod.silex.me) will soon be available on [editor.silex.me](http://editor.silex.me)
And then I'll go back to the mobile editor

**Comment by lexoyo** [comment]
To everyone in this discussion: please check that all the bugs you found are now fixed. (only @AndreaMonzini has a problem with image path?)

And thank you to be part of this :+1:

**Comment by AndreaMonzini** [comment]
Hello,
just checked the last version and it seems to work well.
I have some problems with alignements from editor to the publication.
The website i realized with silex is:

http://www.cleaningyourteeth.com

**Comment by lexoyo** [comment]
This version is live! Well done everyone :fireworks: 
http:///editor.silex.me/

Now that's a pull request! "[Silex] UI improvements, social features, generate better HTML/CSS code"
https:///github.com/silexlabs/Silex/pull/281

Do not hesitate to give feedback here :+1:

**Comment by lexoyo** [comment]
@AndreaMonzini you can share your site with a.hoyau [at] im-paris [dot] fr so that I can check what is wrong with your website
