### ISSUE TITLE
silex fails behind https

### ISSUE THREAD

**Issue by pierreozoux** [silexlabs/Silex#294]
This is because it loads assets over http. This is hardwritten.

As a general advice, it is always better to use `//` instead of hardwriting `http://`

I tried to have an instance here, so you can see the error yourself: https://silex.tokoloho.co/#

I have a commit here but it didn't fix the issue as `static.silex.me` doesn't serve `https`: https://github.com/indiehosters/Silex/commit/5bfe1bfc31fcbd03189aa6f2fdcb61df95b3a92e

**Comment by lexoyo** [comment]
Yes you are right
I'll try to make it work with `//`

**Comment by lexoyo** [comment]
I believe you missed the [dist/client/creation-template.html](dist/client/creation-template.html)

**Comment by pierreozoux** [comment]
Yes I did.

Actually I have to admit that I don't understand the use of the dist folder.
It is usually used to put `built assets`. And though that by modifying the `src`, and using `grunt deploy` it would have erased the dist folder.

But yeah you are right, I totally missed this file.

As a side note, did you read [12factor](http://12factor.net/). I'm telling that for the separation of the `build` `release` and `run` http://12factor.net/build-release-run

**Comment by lexoyo** [comment]
> Actually I have to admit that I don't understand the use of the dist folder.
> It is usually used to put built assets. And though that by modifying the src, and using grunt deploy it would have erased the dist folder.

You are right, and it is what it is used for. Just I left some files which are not build (like assets and libs). But nowadays I would do probably put these files in an "assets" folder and use bower for the libs. That was quite a while ago so..  :)

**Comment by pierreozoux** [comment]
Yeah no problems :)

But it is just that it makes things a bit harder when we don't follow conventions :) I have probably tones of code that also don't follow conventions :)

By the way, I would rename `grunt deploy` to `grunt build` also. And I think it is a good choice to move to npm scripts :)

(sorry for the digression)

**Comment by lexoyo** [comment]
I love digressions :))

**Comment by lexoyo** [comment]
Following this

> Ok I tried and it doesn't work. I tried to enable ssl on our gandi hosting and it is available on a bigger plan. I asked them if they can provide a bigger hosting plan for free (they already offer hosting to be a sponsor)

I had a positive answer from Gandi and we now have a plan which supports HTTPS
So tonight I will try to put static.silex.me on the same hosting as Silex, and handle HTTP and HTTPS out of the box in Silex

**Comment by lexoyo** [comment]
And tell me if you have time to help on that, I could drive you through it

**Comment by pierreozoux** [comment]
Oh it is cool!

I don't have much time, but I'd love to have at least silex.tokoloho.co working :) I think if I just use the indiehosters repo and you offer https on silex.me, it should work just fine.

Then to try if a generated website work, I need to have an ftp or dropbox (which I don't). Isn't it possible to publish locally?

Thanks!

**Comment by pierreozoux** [comment]
I just checked for https, but I have errors on https://static.silex.me/

**Comment by lexoyo** [comment]
hi

for now, https://static.silex.me/ still points to a cdn without support for https

what i plan to do is:

* add support for SSL/https to the [server side script](https://github.com/silexlabs/Silex/blob/master/dist/server/server.js)
* in the [backward compat class](https://github.com/silexlabs/Silex/blob/master/src/js/utils/backward-compat.js), convert all http://static.silex.me/ to //[current silex instance]/static

what do you think?

**Comment by pierreozoux** [comment]
Sounds like a plan :)

**Comment by lexoyo** [comment]
Hi
Silex should now work behind https. See the git branch https://github.com/lexoyo/Silex/tree/https
But for now, https://static.silex.me/ still points to a cdn without support for https. And I still have to handle backward compatibility

**Comment by pierreozoux** [comment]
Still no luck: https://silex.tokoloho.co/# do you have an idea?

**Comment by lexoyo** [comment]
Yes that is because of static.silex.me 
So be patient :)

**Comment by lexoyo** [comment]
I finally made it! :)
You can serve websites made with Silex behind https AND serve Silex itself behind https

This is live on http://preprod.silex.me
Which is the develop branch of silexlabs/Silex, see this PR https://github.com/silexlabs/Silex/pull/313

The preprod server however does not support https so you can make https friendly websites with it, but **https://**preprod.silex.me will not work. Once deployed, the main URL of Silex will be https://editor.silex.me

**Comment by lexoyo** [comment]
One drawback though: 
the protocol agnostic urls make the website buggy when view with the `file://` protocol :-1:  (users often click on the html page)

Maybe I should add the "enable https” option in the params of the website?

**Comment by pierreozoux** [comment]
I don't know what to advise for `file:///`... What is the web saying about that? Maybe there is an elegant way to solve this issue?

About https, sorry to tell you that it is still not working :/ 

`Blocked mixes content`

![silex-fail](https://cloud.githubusercontent.com/assets/1863453/9437312/888a7742-4a4d-11e5-9581-9f8a485a693b.png)

I think this commit (I had to revert because of merging your changes) might help: https://github.com/indiehosters/Silex/commit/fe5f6f77a1c8b0da356bb92fd6c6b528947ed9b4

Thanks for your work :)

**Comment by lexoyo** [comment]
Yes, the changes are not live yet
But if you host the develop branch behind https yourself it should work

**Comment by pierreozoux** [comment]
Ah sorry, but I actually have the same issue here: https://silex.tokoloho.co/#

This is with develop branch.

**Comment by lexoyo** [comment]
Looks like it is not the latest code
For example
https://silex.tokoloho.co/creation-template.html
Should be
https://github.com/silexlabs/Silex/blob/develop/dist/client/creation-template.html

On Mon, Aug 24, 2015 at 4:06 PM, Pierre Ozoux <notifications@github.com>
wrote:

> Ah sorry, but I actually have the same issue here:
> https://silex.tokoloho.co/#
>
> This is with develop branch.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/silexlabs/Silex/issues/294#issuecomment-134217235>.
>



-- 
If you want to keep in touch with Silex Labs subscribe here
<http://eepurl.com/MCCDP>

**Comment by pierreozoux** [comment]
Ok!

Great :) Thank you very much!

https://silex.tokoloho.co/

It is now working :) Please ping me on this issue when it is done on master, then I close the issue and update the Dockerfile :)

Best!

**Comment by lexoyo** [comment]
Ah excellent :dancers: 
If you feel like it we could advertise this instance (silex.tokoloho.co) on the main Silex website? Not sure how, maybe when the user clicks on "Start Now" we should open a "popin" with the list of instances instead of a direct link? Or have 2 buttons... The UI has to be simple at this stage since it is a first contact with the tool

**Comment by pierreozoux** [comment]
Yeah, don't worry for the link. I'll PR the README of this repo when I think I'm ready.

Thanks!

**Comment by singchan** [comment]
fixed
